### ISSUE TITLE
compile eroor

### ISSUE THREAD

**Issue by msalek** [ltoinel/ZWave2MQTT#1]
hello 
can you help me, i have this msg:
thank you .

`root@ubuntu:~/ZWave2MQTT-master# npm install
npm WARN lifecycle openzwave-shared@1.2.9~preinstall: cannot run in wd %s %s (wd=%s) openzwave-shared@1.2.9 node lib/install-ozw.js /home/msalek/ZWave2MQTT-master/node_modules/.staging/openzwave-shared-c8aa07b5

> dtrace-provider@0.8.0 install /home/msalek/ZWave2MQTT-master/node_modules/dtrace-provider
> node scripts/install.js

sh: 1: node: not found
npm WARN install:dtrace-provider@0.8.0 dtrace-provider@0.8.0 install: `node scripts/install.js`
npm WARN install:dtrace-provider@0.8.0 spawn ENOENT

> openzwave-shared@1.2.9 install /home/msalek/ZWave2MQTT-master/node_modules/openzwave-shared
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "console.log(require('./lib/ozwpaths.js').libdir)"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/msalek/ZWave2MQTT-master/node_modules/openzwave-shared
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! openzwave-shared@1.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.2.9 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openzwave-shared
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/msalek/ZWave2MQTT-master/npm-debug.log
`

**Comment by OBerghmans** [comment]
Hi msalek,

I had your issue as well. The "node: not found" indicates that your system already uses the nodejs binary. In Ubuntu, you can install "nodejs-legacy" to get a symlink from node to the nodejs binary. That should get you already further :)
